# Generated by Django 6.1.1 on 2026-10-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_minimal_rag", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="language",
            field=models.CharField(max_length=35, null=True),
        ),
    ]
