# Generated by Django 6.1.1 on 2026-10-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_minimal_rag", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source_key",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
