# Generated by Django 6.1.1 on 2026-10-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_minimal_rag", "0002_alter_document_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="language",
            field=models.TextField(null=True),
        ),
    ]
