# Generated by Django 6.1.1 on 2026-10-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_minimal_rag", "0003_alter_document_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source_key",
            field=models.TextField(unique=True),
        ),
    ]
