# Generated by Django 6.1.1 on 2026-10-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_minimal_rag", "0004_alter_document_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(max_length=2000),
        ),
    ]
