# Generated by Django 6.1.1 on 2026-10-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_minimal_rag", "0004_alter_source_source_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="source_key",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
