# Generated by Django 6.1.1 on 2026-10-08 10:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_minimal_rag", "0006_alter_document_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="permissions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=201), default=list
            ),
        ),
    ]
