# Generated by Django 6.1.1 on 2026-10-08 10:06

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("django_minimal_rag", "0007_document_permissions"),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("embedding_model", models.CharField(max_length=255)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=3)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_minimal_rag.document",
                    ),
                ),
            ],
        ),
    ]
