# Generated by Django 6.1.1 on 2026-10-08 10:08

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_minimal_rag", "0008_chunk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chunk",
            name="embedding",
            field=pgvector.django.vector.VectorField(),
        ),
    ]
