# Generated by Django 6.1.1 on 2026-10-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_minimal_rag", "0009_alter_chunk_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.TextField(),
        ),
    ]
