# Generated by Django 6.1.1 on 2026-10-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_minimal_rag", "0010_alter_document_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="url",
            field=models.TextField(),
        ),
    ]
